### ISSUE TITLE
运行程序时报错

### ISSUE THREAD

**Issue by Cylinder1** [felixBrave/ocr_chinese#17]
Traceback (most recent call last):
  File "D:/google/ocr_chinese-master/ocr_chinese-master/predict.py", line 34, in <module>
    crnn_model.load_weights(crnn_model_weights_file)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 2667, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 3393, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 2372, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variables.py", line 1952, in assign
    name=name)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\ops\state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 69, in assign
    use_locking=use_locking, name=name)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2027, in __init__
    control_input_ops)
  File "D:\music\annnacoda\an\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 11889 and 5990. Shapes are [512,11889] and [512,5990]. for 'Assign_110' (op: 'Assign') with input shapes: [512,11889], [512,5990].
请问如何解决呢

**Comment by JoyChen3014** [comment]
char_std_5990里的内容不对，应该是5990的长度

**Comment by JoyChen3014** [comment]
或者加载的模型不对
